package render

import (
	"encoding/hex"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"

	"github.com/vieitesss/k8s-d2/pkg/model"
)

type D2Renderer struct {
	w io.Writer
}

// NewD2Renderer constructs a D2 renderer.
// gridColumns is deprecated and ignored; D2 now uses automatic layout.
func NewD2Renderer(w io.Writer, gridColumns int) *D2Renderer {
	_ = gridColumns
	return &D2Renderer{
		w: w,
	}
}

func (r *D2Renderer) Render(cluster *model.Cluster) error {
	if cluster == nil {
		return fmt.Errorf("cluster is nil, cannot render")
	}

	cluster = sortedCluster(cluster)

	header := `# Generated by k8s-d2
direction: right

`
	if _, err := fmt.Fprint(r.w, header); err != nil {
		return err
	}

	if err := r.renderLegend(cluster); err != nil {
		return err
	}

	if len(cluster.Namespaces) == 0 {
		return nil
	}

	if _, err := fmt.Fprint(r.w, "namespaces: {\n\n"); err != nil {
		return err
	}

	for _, ns := range cluster.Namespaces {
		if err := r.renderNamespaceIndented(&ns, "  "); err != nil {
			return err
		}
	}

	if _, err := fmt.Fprint(r.w, "}\n"); err != nil {
		return err
	}

	return nil
}

func sortedCluster(cluster *model.Cluster) *model.Cluster {
	namespaces := append([]model.Namespace(nil), cluster.Namespaces...)
	sort.Slice(namespaces, func(i, j int) bool {
		return namespaces[i].Name < namespaces[j].Name
	})

	for i := range namespaces {
		sortNamespace(&namespaces[i])
	}

	return &model.Cluster{
		Name:       cluster.Name,
		Namespaces: namespaces,
	}
}

func sortNamespace(ns *model.Namespace) {
	ns.Deployments = sortedWorkloads(ns.Deployments)
	ns.StatefulSets = sortedWorkloads(ns.StatefulSets)
	ns.DaemonSets = sortedWorkloads(ns.DaemonSets)
	ns.Services = sortedServices(ns.Services)
	ns.PVCs = sortedPVCs(ns.PVCs)
}

func sortedWorkloads(workloads []model.Workload) []model.Workload {
	sorted := append([]model.Workload(nil), workloads...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})
	return sorted
}

func sortedServices(services []model.Service) []model.Service {
	sorted := append([]model.Service(nil), services...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})
	return sorted
}

func sortedPVCs(pvcs []model.PVC) []model.PVC {
	sorted := append([]model.PVC(nil), pvcs...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})
	return sorted
}

func (r *D2Renderer) renderNamespaceIndented(ns *model.Namespace, indent string) error {
	nsID := SanitizeID(ns.Name)
	var b strings.Builder

	fmt.Fprintf(&b, "%s%s: {\n", indent, nsID)
	fmt.Fprintf(&b, "%s  label: %s\n", indent, QuoteString(ns.Name))
	fmt.Fprintf(&b, "%s  style.fill: \"#f0f0f0\"\n\n", indent)

	r.writeAllWorkloads(&b, ns, indent)
	r.writeAllServices(&b, ns, indent)
	r.writeConfigInfo(&b, ns, indent)
	r.writePVCs(&b, ns, indent)
	r.writeConnections(&b, ns, indent)

	fmt.Fprintf(&b, "%s}\n\n", indent)
	if _, err := fmt.Fprint(r.w, b.String()); err != nil {
		return err
	}
	return nil
}

func (r *D2Renderer) writeAllWorkloads(b *strings.Builder, ns *model.Namespace, indent string) {
	for _, w := range ns.Deployments {
		r.writeWorkload(b, &w, indent)
	}
	for _, w := range ns.StatefulSets {
		r.writeWorkload(b, &w, indent)
	}
	for _, w := range ns.DaemonSets {
		r.writeWorkload(b, &w, indent)
	}
}

func (r *D2Renderer) writeAllServices(b *strings.Builder, ns *model.Namespace, indent string) {
	for _, svc := range ns.Services {
		r.writeService(b, &svc, indent)
	}
}

func (r *D2Renderer) writeConfigInfo(b *strings.Builder, ns *model.Namespace, indent string) {
	if ns.ConfigMaps > 0 || ns.Secrets > 0 {
		fmt.Fprintf(b, "%s  _config: {\n", indent)
		fmt.Fprintf(b, "%s    label: %s\n", indent, QuoteString(fmt.Sprintf("CM: %d | Sec: %d", ns.ConfigMaps, ns.Secrets)))
		fmt.Fprintf(b, "%s    style.fill: \"#ffffcc\"\n", indent)
		fmt.Fprintf(b, "%s  }\n", indent)
	}
}

func (r *D2Renderer) writePVCs(b *strings.Builder, ns *model.Namespace, indent string) {
	for _, pvc := range ns.PVCs {
		pvcID := PVCID(pvc.Name)
		label := fmt.Sprintf("💾 %s", pvc.Name)
		if pvc.Capacity != "" {
			label = fmt.Sprintf("%s\n%s", label, pvc.Capacity)
		}
		if pvc.StorageClass != "" {
			label = fmt.Sprintf("%s\n[%s]", label, pvc.StorageClass)
		}
		fmt.Fprintf(b, "%s  %s: {\n", indent, pvcID)
		fmt.Fprintf(b, "%s    label: %s\n", indent, QuoteString(label))
		fmt.Fprintf(b, "%s    style.fill: \"#e6f3ff\"\n", indent)
		fmt.Fprintf(b, "%s  }\n", indent)
	}
}

func (r *D2Renderer) writeWorkload(b *strings.Builder, w *model.Workload, indent string) {
	wID := SanitizeID(w.Name)

	fmt.Fprintf(b, "%s  %s: {\n", indent, wID)
	fmt.Fprintf(b, "%s    label: %s\n", indent, QuoteString(WorkloadLabel(*w)))
	fmt.Fprintf(b, "%s  }\n", indent)
}

func (r *D2Renderer) writeService(b *strings.Builder, svc *model.Service, indent string) {
	svcID := ServiceID(svc.Name)

	fmt.Fprintf(b, "%s  %s: {\n", indent, svcID)
	fmt.Fprintf(b, "%s    label: %s\n", indent, QuoteString(fmt.Sprintf("⎈ %s\n%s", svc.Name, svc.Type)))
	fmt.Fprintf(b, "%s    style.fill: \"#cce5ff\"\n", indent)
	fmt.Fprintf(b, "%s  }\n", indent)
}

func (r *D2Renderer) writeConnections(b *strings.Builder, ns *model.Namespace, indent string) {
	for _, svc := range ns.Services {
		if len(svc.Selector) == 0 {
			continue
		}
		r.writeServiceConnections(b, &svc, ns, indent)
	}

	// Only render workload-to-PVC connections if PVCs are actually present
	if len(ns.PVCs) > 0 {
		r.writeWorkloadPVCConnections(b, ns, indent)
	}
}

func (r *D2Renderer) writeWorkloadPVCConnections(b *strings.Builder, ns *model.Namespace, indent string) {
	workloadGroups := [][]model.Workload{ns.Deployments, ns.StatefulSets, ns.DaemonSets}

	for _, workloads := range workloadGroups {
		for _, w := range workloads {
			if len(w.VolumeMounts) == 0 {
				continue
			}

			workloadID := SanitizeID(w.Name)

			// Group mounts by PVC (handle case where same PVC mounted at multiple paths)
			mountsByPVC := make(map[string][]model.VolumeMount)
			for _, mount := range w.VolumeMounts {
				mountsByPVC[mount.PVCName] = append(mountsByPVC[mount.PVCName], mount)
			}

			pvcNames := make([]string, 0, len(mountsByPVC))
			for pvcName := range mountsByPVC {
				pvcNames = append(pvcNames, pvcName)
			}
			sort.Strings(pvcNames)

			for _, pvcName := range pvcNames {
				mounts := mountsByPVC[pvcName]
				pvcID := PVCID(pvcName)
				label := model.FormatMountLabel(mounts)
				fmt.Fprintf(b, "%s  %s -> %s: %s\n", indent, workloadID, pvcID, QuoteString(label))
			}
		}
	}
}

func (r *D2Renderer) writeServiceConnections(b *strings.Builder, svc *model.Service, ns *model.Namespace, indent string) {
	svcID := ServiceID(svc.Name)
	allWorkloads := [][]model.Workload{ns.Deployments, ns.StatefulSets, ns.DaemonSets}

	for _, workloads := range allWorkloads {
		for _, w := range workloads {
			if LabelsMatch(svc.Selector, w.Labels) {
				wID := SanitizeID(w.Name)
				fmt.Fprintf(b, "%s  %s -> %s\n", indent, svcID, wID)
			}
		}
	}
}

func (r *D2Renderer) renderLegend(cluster *model.Cluster) error {
	entries := legendEntries(cluster)
	if len(entries) == 0 {
		return nil
	}

	var b strings.Builder
	b.WriteString("vars: {\n  d2-legend: {\n")

	for i, entry := range entries {
		fmt.Fprintf(&b, "    %s: {\n", entry.id)
		fmt.Fprintf(&b, "      label: %s\n", QuoteString(entry.label))
		if entry.fill != "" {
			fmt.Fprintf(&b, "      style.fill: %s\n", QuoteString(entry.fill))
		}
		b.WriteString("    }\n")
		if i < len(entries)-1 {
			b.WriteString("\n")
		}
	}

	b.WriteString("  }\n}\n\n")

	if _, err := fmt.Fprint(r.w, b.String()); err != nil {
		return err
	}

	return nil
}

type legendEntry struct {
	id    string
	label string
	fill  string
}

var allLegendEntryIDs = []string{
	"deployment",
	"statefulset",
	"daemonset",
	"service",
	"config",
	"pvc",
}

// LegendEntryIDs returns the legend entry IDs that should be rendered for the cluster.
func LegendEntryIDs(cluster *model.Cluster) []string {
	entries := legendEntries(cluster)
	ids := make([]string, 0, len(entries))
	for _, entry := range entries {
		ids = append(ids, entry.id)
	}
	return ids
}

// AllLegendEntryIDs returns all supported legend entry IDs.
func AllLegendEntryIDs() []string {
	return append([]string(nil), allLegendEntryIDs...)
}

func legendEntries(cluster *model.Cluster) []legendEntry {
	var hasDeployments bool
	var hasStatefulSets bool
	var hasDaemonSets bool
	var hasServices bool
	var hasConfig bool
	var hasPVCs bool

	for _, ns := range cluster.Namespaces {
		hasDeployments = hasDeployments || len(ns.Deployments) > 0
		hasStatefulSets = hasStatefulSets || len(ns.StatefulSets) > 0
		hasDaemonSets = hasDaemonSets || len(ns.DaemonSets) > 0
		hasServices = hasServices || len(ns.Services) > 0
		hasConfig = hasConfig || ns.ConfigMaps > 0 || ns.Secrets > 0
		hasPVCs = hasPVCs || len(ns.PVCs) > 0
	}

	entries := make([]legendEntry, 0, 6)
	if hasDeployments {
		entries = append(entries, legendEntry{
			id:    "deployment",
			label: fmt.Sprintf("%s Deployment", WorkloadIcon("Deployment")),
			fill:  "#f9f9f9",
		})
	}
	if hasStatefulSets {
		entries = append(entries, legendEntry{
			id:    "statefulset",
			label: fmt.Sprintf("%s StatefulSet", WorkloadIcon("StatefulSet")),
			fill:  "#f9f9f9",
		})
	}
	if hasDaemonSets {
		entries = append(entries, legendEntry{
			id:    "daemonset",
			label: fmt.Sprintf("%s DaemonSet", WorkloadIcon("DaemonSet")),
			fill:  "#f9f9f9",
		})
	}
	if hasServices {
		entries = append(entries, legendEntry{
			id:    "service",
			label: "⎈ Service",
			fill:  "#cce5ff",
		})
	}
	if hasConfig {
		entries = append(entries, legendEntry{
			id:    "config",
			label: "ConfigMaps | Secrets",
			fill:  "#ffffcc",
		})
	}
	if hasPVCs {
		entries = append(entries, legendEntry{
			id:    "pvc",
			label: "💾 PVC",
			fill:  "#e6f3ff",
		})
	}

	return entries
}

// SanitizeID converts an arbitrary Kubernetes name into a D2-safe identifier.
// The encoded form avoids collisions from lossy substitutions and keeps
// D2 path syntax from reinterpreting characters like dots.
func SanitizeID(s string) string {
	return "id_" + hex.EncodeToString([]byte(s))
}

// ServiceID returns the rendered D2 identifier for a Service node.
func ServiceID(name string) string {
	return "svc_" + SanitizeID(name)
}

// PVCID returns the rendered D2 identifier for a PVC node.
func PVCID(name string) string {
	return "pvc_" + SanitizeID(name)
}

// QuoteString returns s as a D2 string literal.
func QuoteString(s string) string {
	return strconv.Quote(s)
}

// WorkloadIcon returns the D2 icon for a workload type.
func WorkloadIcon(kind string) string {
	switch kind {
	case "StatefulSet":
		return "◉"
	case "DaemonSet":
		return "◈"
	default:
		return "●"
	}
}

// WorkloadLabel returns the rendered label for a workload node.
func WorkloadLabel(w model.Workload) string {
	icon := WorkloadIcon(w.Kind)
	if w.Kind == "DaemonSet" {
		return fmt.Sprintf("%s %s", icon, w.Name)
	}

	return fmt.Sprintf("%s %s (%d)", icon, w.Name, w.Replicas)
}

// LabelsMatch checks if a selector matches a set of labels.
// All selector key-value pairs must match the labels for this to return true.
func LabelsMatch(selector, labels map[string]string) bool {
	if len(selector) == 0 {
		return false
	}

	for key, value := range selector {
		if labels[key] != value {
			return false
		}
	}
	return true
}
